### ISSUE TITLE
no default export

### ISSUE THREAD

**Issue by rodmerritt** [raminahmadi1986/SPFileUpload#1]
When i run the project Gulp Serve I get the following error. Any ideas?

SPFileUpload-master/node_modules/react-dropzone-component/typescript/types"' has no default export.

**Comment by AhmadiRamin** [comment]
please download the package-lock.json and copy the file to the root folder and run npm install again. it should solve the problem.

**Comment by rodmerritt** [comment]
I tried to re-clone and start over but still getting same error

**Comment by AhmadiRamin** [comment]
I tried to clone it in a different folder and I got your error message after running gulp serve, downgrade the react-dropzone-component fixed the problem for me:
**run npm uninstall react-dropzone-component
run npm install react-dropzone-component@3.0.0**
hope this can solve your problem.

**Comment by rodmerritt** [comment]
It is now working thanks for the instruction
